version: "3.7"

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        - NEXT_PUBLIC_BASE_URL=http://server:8000
    ports:
      - "3000:3000"
    container_name: client
    stdin_open: true
    tty: true # Keeps the container running for debugging
    networks:
      - prisma-network

  postgres_db:
    image: postgres:15
    hostname: postgres_db
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
    ports:
      - "5432:5432"
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20

  server:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    container_name: server
    stdin_open: true
    tty: true # Keeps the container running for debugging
    depends_on:
      postgres_db:
        condition: service_healthy
    env_file:
      - .env.prod
    networks:
      - prisma-network

  prisma-studio:
    image: node:lts-alpine3.17
    working_dir: /usr/src/app/server
    volumes:
      - .:/usr/src/app
    command: npx prisma studio --port 5555 --browser none
    container_name: prisma-studio
    ports:
      - "5555:5555"
    env_file:
      - .env.prod
    networks:
      - prisma-network
    depends_on:
      postgres_db:
        condition: service_healthy
      server:
        condition: service_started

networks:
  prisma-network:
    name: prisma-network
